#! /bin/sh
# bootstrap -- again, this is taken from Gary V. Vaughan's
# excellent autotools book (http://sources.redhat.com/autotools).

## @start 1
#! /bin/sh

set -x
autopoint
aclocal -I config $@
autoheader
automake --add-missing --copy
autoconf
## @end 1
