#! /bin/sh
# bootstrap -- again, this is taken from Gary V. Vaughan's
# excellent autotools book (http://sources.redhat.com/autotools).

## @start 1
#! /bin/sh

set -x
aclocal -I config $@
autoheader
automake --verbose --add-missing --copy -W all
autoconf
## @end 1
